# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x12\x05\x63hord\" \n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"\x04\n\x02\x45R\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xb4\x01\n\x05\x43hord\x12(\n\x0eGetPredecessor\x12\t.chord.ER\x1a\x0b.chord.Node\x12&\n\x0cGetSuccessor\x12\t.chord.ER\x1a\x0b.chord.Node\x12\'\n\rFindSuccessor\x12\t.chord.ID\x1a\x0b.chord.Node\x12\x30\n\x16\x43losestPrecedingFinger\x12\t.chord.ID\x1a\x0b.chord.Nodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODE']._serialized_start=22
  _globals['_NODE']._serialized_end=54
  _globals['_ER']._serialized_start=56
  _globals['_ER']._serialized_end=60
  _globals['_ID']._serialized_start=62
  _globals['_ID']._serialized_end=78
  _globals['_CHORD']._serialized_start=81
  _globals['_CHORD']._serialized_end=261
# @@protoc_insertion_point(module_scope)
